backzer/admin/models.py
from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import InputRequired, AnyOf


class NewUserForm(Form):
    username = StringField('Username', [InputRequired()])
    password = PasswordField('Password', [InputRequired()])
    auth_method = PasswordField('Password', [AnyOf(['local', 'ldap'])])
    is_admin = PasswordField('Password', [AnyOf(['true', 'false'])])

backzer/host/models.py
from backzer import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    hostname = db.Column(db.String(100), nullable=False, unique=True)
    ip = db.Column(db.String(100), nullable=False)
    os = db.Column(db.String, primary_key=True)
    status = db.Column(db.String(100))
    enabled = db.Column(db.Boolean, default=True)

    def __init__(self, hostname, ip, os, status, enabled=True):
        self.hostname = hostname
        self.ip = ip
        self.os = os
        self.status = status
        self.enabled = enabled

backzer/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from sqlalchemy.exc import IntegrityError
from configobj import ConfigObj
from backzer.auth.password import Password


config = ConfigObj('../config.ini')


# Set up the application
app = Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////tmp/test.db'
app.config['WTF_CSRF_SECRET_KEY'] = 'random key for form'
app.config['LDAP_PROVIDER_URL'] = 'ldap://ldap.testathon.net:389/'
app.config['LDAP_PROTOCOL_VERSION'] = 3
app.config['USER_EMAIL_SENDER_EMAIL'] = 'root@localhost'
db = SQLAlchemy(app)

app.secret_key = 'some_random_key'


login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login'

from backzer.auth.views import auth
from backzer.admin.views import admin

app.register_blueprint(auth)
app.register_blueprint(admin)


from backzer.auth.models import User

db.create_all()




try:
    if bool(config['ADMIN']['enabled']):
        # Try to get the admin user
        admin = db.session.query(User).filter_by(id=1).first()
        if admin:
            admin.username = config['ADMIN']['local_admin_user']
            admin.password = Password.hash_password(config['ADMIN']['local_admin_password'])
            admin.auth_method = 'local'
            admin.is_admin = True
        else:
            admin = User(config['ADMIN']['local_admin_user'], Password.hash_password(config['ADMIN']['local_admin_password']), True, 'local')
            admin.id = 1
            db.session.add(admin)
        db.session.commit()
except IntegrityError:
    raise

backzer/admin/views.py
from flask import  render_template, Blueprint
from flask import flash, redirect, url_for
from flask_login import current_user, login_required
from backzer import app, db
from backzer.auth.models import User
from backzer.admin.models import NewUserForm
from flask import request
from backzer.auth.password import Password
from sqlalchemy.exc import IntegrityError


admin = Blueprint('admin', __name__)

@admin.route('/admin')
@login_required
def base():
    if current_user.is_authenticated:
        if not current_user.is_admin:
            flash('User error, please contact site administrator.', 'danger')
            return redirect(url_for('auth.home'))

        return render_template('admin/base.html')

@admin.route('/admin/configuration')
@login_required
def configuration():
    """
    This view is for displaying the current configuration in non-editable format. The admin must edit the configuration
    in the config.ini file and restart the application!
    :return:
    """
    if current_user.is_authenticated:
        if not current_user.is_admin:
            flash('User error, please contact site administrator.', 'danger')
            return redirect(url_for('auth.home'))

        import pprint
        pprint.pprint(app.config)

        return render_template('admin/configuration.html', config=app.config)


@admin.route('/admin/user', methods=['GET', 'POST'])
@login_required
def user():
    if current_user.is_authenticated:
        if not current_user.is_admin:
            flash('User error, please contact site administrator.', 'danger')
            return redirect(url_for('auth.home'))

        form = NewUserForm(request.form)

        if request.method == 'POST' and form.validate():
            username = request.form.get('username')
            password = Password.hash_password(request.form.get('password'))
            auth_method = request.form.get('auth_method')

            if request.form.get('is_admin') == "true":
                is_admin = True
            else:
                is_admin = False

            try:
                User.create_user(username, password, bool(is_admin), auth_method)
                flash("New user has been added successfully!", 'success')
            except IntegrityError:
                db.session.rollback()
                flash("This username has already been taken, please choose a different one!", 'danger')

        if form.errors:
            flash(form.errors, 'danger')

        return render_template('admin/new_user.html', form=form)

@admin.route('/admin/users')
@login_required
def users():
    if current_user.is_authenticated:
        if not current_user.is_admin:
            flash('User error, please contact site administrator.', 'danger')
            return redirect(url_for('auth.home'))

        users = User.get_users()
        return render_template('admin/list_users.html', users=users)

backzer/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Authentication with LDAP Tutorial</title>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
</head>
<body>
<div class="container bg-white">
        {% include 'nav.html' %}
        <div>
            {% for category, message in get_flashed_messages(with_categories=true) %}
            <br>
            <div class="alert alert-{{category}} alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% block container %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {% block scripts %}
    {% endblock %}
</div>
</body>
</html>

backzer/templates/cards.html
{% block cards %}
<div class="mt-2 col-md-12"></div>
    <div class="card-columns">
        <div class="card bg-primary">
            <div class="card-body text-center">
                <p class="card-text">Number of added hosts</p>
                <p class="h2">451</p>
            </div>
        </div>
        <div class="card bg-warning">
            <div class="card-body text-center">
                <p class="card-text">Number of running tasks</p>
                <p class="h2">10</p>
            </div>
        </div>
        <div class="card bg-danger">
            <div class="card-body text-center">
                <p class="card-text">Number of failed backups</p>
                <p class="h2">1</p>
            </div>
        </div>
    </div>
{% endblock %}

backzer/templates/home.html
{% extends 'base.html' %}
{% block container %}
{% include 'cards.html' %}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Hostname</th>
      <th scope="col">IP</th>
      <th scope="col">OS</th>
      <th scope="col">Status</th>
      <th scope="col">Last Changed</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Router1</td>
      <td>1.1.1.1</td>
      <td>IOS</td>
      <td>OK</td>
      <td>2019.01.01 14:33</td>
      <td>LatestConfig Backup</td>
    </tr>
    <tr>
      <td>Firewall1</td>
      <td>3.4.5.6</td>
      <td>ASA</td>
      <td>WIP</td>
      <td>2012.01.01 14:33</td>
      <td>LatestConfig Backup</td>
    </tr>

  </tbody>
</table>
{% endblock %}

backzer/templates/login.html
{% extends 'home.html' %}


{% block container %}
<form method="POST" action="{{ url_for('auth.login') }}" role="form">
    {{ form.csrf_token }}
    <div class="form-group">
    <div class="col-md-4 mb-3">
        <label for="username" class="col-sm-2 col-form-label">{{ form.username.label }}</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="username" name="username" placeholder="Username">
        </div>
    </div>
    <div class="col-md-4 mb-3">
        <label for="password" class="col-sm-2 col-form-label">{{ form.password.label }}</label>
        <div class="col-sm-10">
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
    </div>
    <div class="col-md-4 mb-4">
        <label for="inputState" class="col-sm-2 col-form-label">Auth-Method</label>
        <div class="col-sm-10">
            <select id="inputState" class="form-control" name="authmethod">
                <option selected>LDAP</option>
                <option>Local</option>
            </select>
        </div>
    </div>
     <div class="col-sm-10">
    <button type="submit" class="btn btn-primary">Sign in</button>
     </div>
    </div>
</form>
{% endblock %}

backzer/templates/nav.html
{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{{ url_for('auth.home') }}">BackZer</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Documentation</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">API</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Reload hosts</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-auto">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <ul class="navbar-nav ml-auto">
                {% if current_user.is_admin %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('admin.base') }}">Admin</a>
                    </li>
                {% endif %}
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">{{ current_user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock %}